services:

  postgres:
    image: postgres:16
    container_name: data_platform_db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: data_platform

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  n8n:
    image: n8nio/n8n
    container_name: data_platform_n8n

    ports:
      - "5678:5678"

    volumes:
      - n8n_data:/home/node/.n8n


volumes:
  postgres_data:
  n8n_data: